# If not set, defaults to the directory name of `source_path`
name: 'Test-app'

# Path is relative to the location of the configuration file and specifies
# the root to expand all paths from
# If not set, defaults to a git repository root
# root: './'

# Path is relative to configuration root
# If not set, defaults to '.licenses'
# cache_path: ''

# Path is relative to configuration root and specifies the working directory when enumerating dependencies
# Optional for single app configuration, required when specifying multiple apps
# Defaults to current directory when running `licensed`
# source_path: './'

# Sources of metadata
sources:
  yarn: true
  bundler: true

# Dependencies with these licenses are allowed by default.
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - wtfpl

# These dependencies are explicitly ignored.
ignored:
  # bundler:
  #   - some-internal-gem

  # yarn:
  #   - some-internal-package

# These dependencies have been reviewed.
reviewed:
  bundler:
